abbr --add gs 'git status'
abbr --add gd 'git diff'
abbr --add gds 'git diff --staged'
abbr --add gsh 'git show'
abbr --add ga 'git add'
abbr --add gc 'git commit'
abbr --add gca 'git commit --amend'
abbr --add gp 'git push'
abbr --add gpf 'git push --force-with-lease'
abbr --add gl 'git pull'
abbr --add glr 'git pull --rebase'
abbr --add gr 'git reset'
abbr --add grh 'git reset --hard'
abbr --add gcl 'git clone'
abbr --add gb 'git branch'
abbr --add gf 'git fetch'
abbr --add gss 'git stash save'
abbr --add gsl 'git stash list'
abbr --add gsp 'git stash pop'
abbr --add grb 'git rebase'
abbr --add gcp 'git cherry-pick'
abbr --add gm 'git merge'
abbr --add gmm 'git merge --no-ff'
abbr --add grs 'git restore'
abbr --add grss 'git restore --staged'
abbr --add gsw 'git switch'
abbr --add gswd 'git switch -d'
abbr --add gswc 'git switch -c'
