#!/usr/bin/env fish

set -l fish_functions ~/.config/fish/functions
set -l helix_config ~/.config/helix
set -l nvim_colors ~/.config/nvim/colors
set -l nvim_snippets ~/.config/nvim/snippets

cd (dirname (status -f))
pwd

echo 'Creating symlinks...'
echo ''

echo '~/.config/kitty/kitty.conf'
mkdir ~/.config/kitty
ln -s (pwd)/kitty/kitty.conf ~/.config/kitty/kitty.conf

echo '~/.config/kitty/ssh.conf'
ln -s (pwd)/kitty/ssh.conf ~/.config/kitty/ssh.conf

echo '~/.config/kitty/themes'
ln -s (pwd)/kitty/themes ~/.config/kitty/themes

echo '~/.config/fish/config.fish'
ln -s (pwd)/fish/config.fish ~/.config/fish/config.fish

if [ -d $fish_functions ]
    echo $fish_functions ' already exists'
else
    echo $fish_functions
    ln -s (pwd)/fish/functions $fish_functions
end

if [ -d $helix_config ]
	echo $helix_config' already exists'
else
	echo $helix_config
	ln -s (pwd)/helix $helix_config
end

echo '~/.config/nvim/init.lua'
ln -s (pwd)/nvim/init.lua ~/.config/nvim/init.lua

if [ -d $nvim_colors ]
	echo $nvim_colors ' already exists'
else
	echo $nvim_colors
	ln -s (pwd)/nvim/colors $nvim_colors
end

if [ -d $nvim_snippets ]
	echo $nvim_snippets ' already exists'
else
	echo $nvim_snippets
	ln -s (pwd)/nvim/snippets $nvim_snippets
end

echo '~/.gitconfig'
ln -s (pwd)/git/.gitconfig ~/.gitconfig

echo '~/.gitconfig-yumpu'
ln -s (pwd)/git/.gitconfig-yumpu ~/.gitconfig-yumpu

echo '~/.config/git/ignore'
mkdir
ln -s (pwd)/git/.gitignore ~/.config/git/ignore

echo '~/.ackrc'
ln -s (pwd)/ack/.ackrc ~/.ackrc

echo '~/.editorconfig'
ln -s (pwd)/nvim/.editorconfig ~/.editorconfig
