#!/usr/bin/env fish

cd (dirname (status -f))
pwd

echo 'Creating symlinks...'
echo ''

echo '~/.gitconfig'
ln -s (pwd)/git/gitconfig.symlink ~/.gitconfig

echo '~/.config/fish/config.fish'
ln -s (pwd)/fish/config.fish.symlink ~/.config/fish/config.fish

echo '~/.config/nvim/init.vim'
ln -s (pwd)/nvim/init.vim.symlink ~/.config/nvim/init.vim
