[[language]]
name = "css"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "fish"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "javascript"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "json"
indent = {tab-width = 4, unit = "\t"}
[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "package.json" ]
url = "https://json.schemastore.org/package.json"

[[language]]
name = "html"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "sql"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "xml"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "yaml"
indent = {tab-width = 4, unit = "    "}
[language-server.yaml-language-server.config.yaml.schemas]
"https://api.bitbucket.org/schemas/pipelines-configuration" = "bitbucket-pipelines.yml"
"https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json" = "docker-compose.yaml"
