[[language]]
name = "css"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "fish"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "javascript"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "json"
indent = {tab-width = 4, unit = "\t"}
[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "package.json" ]
url = "https://json.schemastore.org/package.json"

[language-server.phpactor]
command = "phpactor"
args = [ "language-server", "--config-extra={\"language_server_completion.trim_leading_dollar\":true}" ]
[[language]]
name = "php"
language-servers = [ "phpactor" ]
indent = {tab-width = 4, unit = "\t"}
block-comment-tokens = {start = "/*", end = "*/"}

[[language]]
name = "vue"
indent = {tab-width = 4, unit = "\t"}
language-servers = ["typescript-language-server"]
[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/opt/homebrew/lib/node_modules/@vue/language-server/"
languages = ["vue"]

[language-server.yaml-language-server.config.yaml.schemas]
"https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json" = "docker-compose.yaml"
