abbr --add d 'docker'
abbr --add dc 'docker compose'
abbr --add dcu 'docker compose up'
abbr --add dcuw 'docker compose up --watch'
abbr --add dce 'docker compose exec'
abbr --add dcepf 'docker compose exec php-fpm'
abbr --add dcb 'docker compose build'
abbr --add dr 'docker run'
abbr --add dri 'docker run -it'
